language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: m+1Eek6UUAftoo8RS+hxxxTcCuYrxP2iakFHh8j2PG6gMl0FJBHVg8a2jTLvIinmxbbA3UMqVsJEhWU9W/MRMhgQwFY4mLopcAhu1mcta0Xl7T2BVcmwNoWhi2ZO2TGPfBWpTkblFbqsokUtFKS3azndD40MSB1dN0pjMwocQXk=
  file:
    - 'emoji-emotion.js'
    - 'emoji-emotion.min.js'
  on:
    tags: true
